[[plugins]]
repo = 'Shougo/dein.vim'
# ====================
# 見た目周り
# ====================
# テーマ
[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'
hook_add = '''
  set t_Co=256
  set background=dark
  syntax on
  colorscheme hybrid_reverse
  highlight Normal ctermbg=none
  highlight NonText ctermbg=none
  highlight TablineSel ctermbg=none
  highlight LineNr ctermbg=none
  highlight CursorLineNr ctermbg=none
'''

# パワーライン
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline_powerline_fonts = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
let g:airline#extensions#hunks#enabled = 0
'''

# パワーラインのテーマ
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme='papercolor'
  let g:airline#extensions#ale#enabled = 1
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
  let g:indent_guides_exclude_filetypes = ['help', 'nerdtree', 'tagbar', 'unite']
'''

# 見た目綺麗に揃えるやつ
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
  au FileType markdown vmap <Bslash><Bslash> :EasyAlign*<Bar><Enter>
'''

# =-=-=-=-=-=-=-=-=-=-=
# 大事なやつ
# =-=-=-=-=-=-=-=-=-=-=
# 非同期処理を実現してくれるやつ
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'

# htmlタグ補完
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  let g:user_emmet_leader_key='<C-Q>'
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_warning = '**'
  let g:LanguageClient_serverCommands = {
      \ 'vue': ['vls'],
      \ }
  let g:ale_fixers = {
      \ 'javascript': ['eslint'],
      \ 'python': ['autopep8']
      \ }
  let g:ale_linters = {
      \ 'python': ['flake8']
      \ }
  let g:ale_sign_column_always = 1
  let g:ale_lint_on_enter = 0
  let g:ale_lint_on_text_changed = 'never'
  let g:ale_open_list = 0
  let g:ale_keep_list_window_open = 0
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_wargin_str = 'W'
  let g:ale_echo_msg_format = '[%severity%] %s [%linter%]'
'''

# ====================
# ファイル操作周り
# ====================
# ファイルツリーのやつ
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
    nmap <Leader><Tab> <C-w>w
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

# ====================
# Git関連
# ====================
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
