[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']
hook_add = '''
  let g:html5_event_handler_attributes_complete = 0
'''

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css']

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']
