########################################
# python
########################################

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_post_source = '''
  let g:deoplete#sources#jedi#show_docstring = 0
'''

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'
